### PR TITLE
Re-creating PR To fix CSTR configuration bug

### PR DESCRIPTION
**Pull request by andrewlee94**
**NOTE:** When this PR is approved, you *must* do the following so it can be merged:
* Add the "approved" tag to the pull-request
* Trigger tests by pushing a commit or manually re-running in CircleCI

See [this wiki page](https://github.com/IDAES/idaes-dev/wiki/Github-Pull-Request-Workflow-with-Approval-Tag) for details.

----
## Summary/Motivation:
A bug was found where the wrong argument from the config block was being used in creating the material balance constraints for the CSTR model (affected cases with chemical equilibrium).

This is a re-creation of PR #45 to address some lingering issues with the switch to the open repository.

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

----

## Reviewer Checklist
* Reviewer 1
- [ ] Tests: do they pass, do they cover functionality, are they understandable?
- [ ] Documentation: is the code commented, are there user-level docs where needed?
* Reviewer 2
- [ ] Tests: do they pass, do they cover functionality, are they understandable?
- [ ] Documentation: is the code commented, are there user-level docs where needed?

### CODE REVIEW

**Review by lbianchi-lbl — APPROVED** [review]
Looks good. Sorry again for this branch business, but most likely it won't be a problem anymore going forward.

**Review by jghouse88 — APPROVED** [review]
LGTM. Do we have any CI tests running to go ahead and merge this?

**Comment by lbianchi-lbl** [comment]
Checking if commenting is enough to trigger the CI on a PR created prior to merging #54.

**Review by lbianchi-lbl — APPROVED** [review]
Re-approving for the CI

**Pull request merged**
