### PR TITLE
Add CI job for compatibility testing

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Summary/Motivation:
- Enable compatibility testing (using [IDAES/idaes-compatibility](https://github.com/IDAES/idaes-compatibility)) for PRs

## Changes proposed in this PR:

- Add job for compatibility testing to core CI workflow

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — APPROVED** [review]

**Comment by lbianchi-lbl** [comment]
@andrewlee94 I think we now have only "good" failures, i.e. meaningful compatibility errors, as opposed to failures due to missing data files.

**Comment by andrewlee94** [comment]
@lbianchi-lbl Yes, those look like real failures now. I suspect a number of them are due to changes @eslickj made to the Helmholtz EoS packages, whilst a few are due to a known issue about changes I made to the metadata.

**Comment by lbianchi-lbl** [comment]
@andrewlee94 FYI, these are the tests that are still failing after switching to IDAES/idaes-compatibility#9:

image

**Comment by lbianchi-lbl** [comment]
Compatibility tests have been added to the required PR checks: 
image

**Pull request merged**
