### PR TITLE
Add Save functionality to flowsheet visualizer (IFV)

### LINKED ISSUE #101: Add IFV save/restore from Jupyter
For the IDAES Flowsheet Visualizer, add functionality from Jupyter Notebooks that lets you set the save/restore location for the layout and other values that can get modified by the IFV itself.

### PR DESCRIPTION
**Pull request by dangunter**
## Fixes #101 

This should go at about the same time as #100 , so the docs can reflect all these changes.

## Summary/Motivation:
Need a better save/restore

## Changes proposed in this PR:
- Big refactor of the backend for diffing and merging flowsheets
- Refactor of HTTP server architecture, go from two servers to one, drop flask and use embedded HTTP
- Minor refactor of UI to talk to new backend (at least compared to refactors in previous two items)
- Rewrite of affected tests, of course

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by dangunter** [comment]
Note, this is still WIP for a couple more days. Just wanted to make people aware it's coming.

**Comment by dangunter** [comment]
@ksbeattie and @lbianchi-lbl, I realize this is not exactly what you're working on, and it's sort of a monster. But I need 2 reviewers or I'm just going to admin-merge it. Happy to answer questions.

**Review by lbianchi-lbl — COMMENTED** [review]
I did a quick readthrough and nothing jumped to my eye, so I'm happy to rubber-stamp.

The only thing I could mention is about the files `idaes/ui/tests/demo_flowsheet.json` and `idaes/ui/tests/test_flowsheet.json`. Currently, they're formatted on a single line, which is OK if they're supposed to be machine- rather than human-readable. If however you think they could be modified or extended in the future (e.g. when new visualization functionality will be added), it would be difficult to read the (linewise) diff.

**Comment by makaylas** [comment]
How is the save supposed to work now? I either couldn't figure out where it saved or it didn't save. I assumed that when you clicked save it would pop up a dialog so I can show it where to save but maybe that isn't the correct assumption.

Does there need to be any user documentation updates to reflect the new saving?

Also the export to SVG isn't working

**Comment by dangunter** [comment]
@makaylas the documentation is in a separate PR. Save goes where you told it to when you invoked the visualize() function.

**Comment by dangunter** [comment]
This will get merged today barring any obvious major problems. @makaylas please look if you have time, and if you find errors try to be specific about what the output was and (looking at the code) what is wrong. Thanks!

**Review by makaylas — APPROVED** [review]

**Pull request merged**
