### PR TITLE
Remove support for Python 3.8

### LINKED ISSUE #1462: Drop support for Python 3.8
Python 3.8 is related to a growing number of issues, mostly due to support being dropped by dependencies such as NumPy and matplotlib, including:

- #1401
- #1453

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Changes proposed in this PR:
- Remove Python 3.8 from supported versions in docs and `setup.py`
- Remove Python 3.8 from CI workflows

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by bpaul4 — APPROVED** [review]
Just one non-critical comment.

There is one mention on Python 3.8 on the FAQ page: https://github.com/IDAES/idaes-pse/blob/main/docs/explanations/faq.rst. The `pywin32` issue may be relevant to other Python version, in which case we could leave the FAQ as-is.

**Comment by lbianchi-lbl** [comment]
> Just one non-critical comment.
> 
> There is one mention on Python 3.8 on the FAQ page: https://github.com/IDAES/idaes-pse/blob/main/docs/explanations/faq.rst. The `pywin32` issue may be relevant to other Python version, in which case we could leave the FAQ as-is.

Good point, I did notice this as well and opted for leaving it in for the same reason you mentioned. I propose to leave that in unless someone objects.

**Comment by andrewlee94** [comment]
@lbianchi-lbl @bpaul4 I suggest we keep the discussion as well, but add a note to indicate that Python 3.8 is no longer officially supported (i.e. make it clear we left this comment there for those who wish to try (or have similar issues), but that we don't guarantee that the rest of the code will work).

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl @bpaul4 I suggest we keep the discussion as well, but add a note to indicate that Python 3.8 is no longer officially supported (i.e. make it clear we left this comment there for those who wish to try (or have similar issues), but that we don't guarantee that the rest of the code will work).

@andrewlee94 I've added a note there (and the same to `README.md` for good measure):

image

**Review by ksbeattie — APPROVED** [review]
LGTM

**Pull request merged**
