### PR TITLE
Categorize variables and constraints in Caprese

### PR DESCRIPTION
**Pull request by Robbybp**
## Summary/Motivation:
This PR extends Caprese's functionality for variable categorization of DAEs (into "differential," "algebraic," etc.) to constraints, and makes the functionality more robust. The categorization is more robust in the sense that differential variables that are "specified" by inputs (such as differential variables at the boundaries of a 1D control volume) are automatically added to the algebraic subsystem, which is required for this subsystem to be square. 
Being able to automatically identify a square algebraic subsystem has significant implications, most notably automatic verification of the index-1 assumption/requirement for DAEs.

This PR relies on https://github.com/Pyomo/pyomo/pull/1888

## Changes proposed in this PR:
- `categorize_dae_variables_and_equations` function in the `idaes.apps.caprese.categorize` module
- example using automatic identification of the algebraic Jacobian to automatically identify the "derivative Jacobian" and perform timescale model reduction on a CSTR
- update the `DynamicBlock` class to relax assumptions about what categories of variables will be present. I now encourage the user to "set up Caprese" in three steps: 1. "Flatten" their model with respect to time, 2. Categorize the variables and equations of their model, and 3. Construct the proper `Block` subclass, which now takes variable categories as an argument (rather than automatically categorizing under the hood).

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by Robbybp** [comment]
The Pyomo PR this relied on was merged last week. Just updated for the new API.

**Comment by ksbeattie** [comment]
@Robbybp any update on this?

**Comment by Robbybp** [comment]
@ksbeattie Waiting for review

**Comment by Robbybp** [comment]
This PR has been updated to rely on the `OrderedSet.card` method.

**Comment by blnicho** [comment]
@Robbybp I updated the Pyomo version in setup.py to (hopefully) get the tests passing again. #463 should be merged before this one.

**Review by jsiirola — COMMENTED** [review]
Apart from one embedded constant, this looks pretty good.

**Review by blnicho — APPROVED** [review]
I found one typo in a test name but otherwise this looks fine.

**Review by jsiirola — APPROVED** [review]
This looks reasonable to me.

**Review by blnicho — APPROVED** [review]

**Review by jsiirola — APPROVED** [review]

**Review by blnicho — APPROVED** [review]

**Pull request merged**
