### PR TITLE
Fix mixer init logging

### PR DESCRIPTION
**Pull request by eslickj**
Update some outdated initialization output level code in the mixed. 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — APPROVED** [review]
No problems here.

**Review by MAZamarripa — DISMISSED** [review]
lgtm

**Review by lbianchi-lbl — APPROVED** [review]
@eslickj @andrewlee94 the "Run examples" jobs in the integration tests now pass, but they still show up as failed PR checks since they come from a different trigger event type (`pull_request_review` vs `pull_request`); this is surprising to me, as I thought that only the job name (and not the trigger event type) were used by GitHub to identify the checks.

I'm leaving this review which should start the jobs with the correct trigger event type.

**Review by andrewlee94 — APPROVED** [review]
Looks good.

**Comment by andrewlee94** [comment]
@MAZamarripa Could you re-approve this please? There was a minor conflict created when I merged the solver update.

**Review by MAZamarripa — APPROVED** [review]
lgtm

**Pull request merged**
