### PR TITLE
[PySMO] Generate Pyomo expression for Kriging prediction uncertainty

### PR DESCRIPTION
**Pull request by adowling2**
## Summary/Motivation:
Currently, PySMO supports generating a Pyomo expression for the Kriging prediction (GP prediction mean). This PR adds the capability to generate Pyomo expression for the uncertainty in the Kriging prediction (GP prediction standard deviation/covariance).

## Changes proposed in this PR:
- [ ] Add `generate_expression_std_dev` function to `kriging.py`
- [ ] Add PyTests
- [ ] Add example to embed expressions for prediction expected value and prediction standard deviation in Pyomo.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by adowling2** [comment]
Currently, PySMO uses (2.40) in Forrester et al to compute the Kriging prediction.

(2.23) and (2.24) in Rasmussen et al give the Gaussian process prediction mean and standard deviation.

Next steps:
- [ ] Compare (2.40) in Forrester to (2.23) in Rasmussen.
- [ ] Write (2.24) from Rasmussen using the notation of (2.40) in Forrester.
- [ ] Understand the correspondence between (2.40) in Forrester and the current PySMO code.
- [ ] Implement standard deviation expression in PySMO.

**Comment by ksbeattie** [comment]
@adowling2, let me know if you disagree with this having "normal" priority and scheduled for the Nov release.

**Comment by adowling2** [comment]
@ksbeattie Works for now.

**Comment by ksbeattie** [comment]
@adowling2, moving this to the Feb release.

**Comment by ksbeattie** [comment]
@adowling2, moving this to May...

**Comment by andrewlee94** [comment]
@adowling2 Is there any update on the status of this? It looks like there has been no progress for 9 months.

**Comment by adowling2** [comment]
This is a non-IDAES funded side project. We can close the PR if you want.

**Comment by adowling2** [comment]
@elvis1090 @jialuw96 Let’s discuss this next week.

**Pull request closed without merging**
