### PR TITLE
RBF patch for basis function display.

### LINKED ISSUE #1164: "gaussian" rbf type always displayed when loading surrogate using `PysmoSurrogate.load_from_file()`
I performed independent surrogate training for all radial basis functions using the config argument in  `PysmoRBFTrainer()` When training, the terminal display is for example,
```
Default parameter estimation method is used.

Parameter estimation method:  algebraic
Basis function:  imq
Regularization done:  True
```
The main thing is that it correctly reports the basis function.

However, when reloading ANY of the surrogates with various rbf's using `PysmoSurrogate.load_from_file()`, the terminal output ALWAYS shows
```
Default parameter estimation method is used.

Parameter estimation method:  algebraic
Gaussian basis function is used.
Basis function:  gaussian
Regularization done:  True
```
 This may be a problem in line 318 of idaes\core\surrogate\pysmo\radial_basis_function.py, but not certain

**EDIT** @lbianchi-lbl : this is the line mentioned: https://github.com/IDAES/idaes-pse/blob/f9c4fd319a590a839007db2605543b523904fa86/idaes/core/surrogate/pysmo/radial_basis_function.py#L318

### PR DESCRIPTION
**Pull request by OOAmusat**
## Fixes
#1164 

## Summary/Motivation:
Fix basis function reported for RBF when using PysmoSurrogate.load_from_file()

## Changes proposed in this PR:
- Passes basis function type into dummy RBF call, ensuring right basis function is printed to screen.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by OOAmusat** [comment]
@andrewlee94 could you please check that this fixes the problem on your end as well?

**Comment by andrewlee94** [comment]
@OOAmusat You would need to tell me what to do to test/replicate this issue. However, I think a better solution would be to have tests which checks this behaviour which will also help prevent regressions.

**Comment by OOAmusat** [comment]
@andrewlee94 It wasn't an error. 

The way the loading function works is that we create a dummy class (with the default RBF settings) to initialize the object with the necessary attributes,  and then populate the values of those attibutes from the saved file. What is printed to screen is from the dummy class initialization, not the final object returned to the user.

What I have done now is to pass in the actual basis function when creating the dummy attribute so that the correct basis function is displayed.

We already have tests that check that the right attributes are actually loaded into the model.

**Comment by andrewlee94** [comment]
The end result might have been right, but the printed output was unexpected and that is a bug/issue. You should add a test for this use case that checks the output to the user and verifies that it is what is expected.

**Review by andrewlee94 — APPROVED** [review]

**Review by bpaul4 — APPROVED** [review]
The change to the main PySMO file makes sense to me. I'm less familiar with the dictionary you check against in the new test, but if it's just a normal output assertion then it looks good to me as well.

**Pull request merged**
