### PR TITLE
Adding a toggle feature to turn off the stream brushing

### PR DESCRIPTION
**Pull request by elbashandy**
## Summary/Motivation:
Adds the capability to turn off the stream brushing/highlighting feature

Screen Shot 2022-02-09 at 11 33 04 AM

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by dangunter** [comment]
Nitpick:
I would have the menu items spelled like this:
`Stream table`
`Stream highights`

**Comment by dangunter** [comment]
Actually thinking about it more, the 3rd item is different. Can you do a divider in the list? e.g.

**View**
  ✔️ Flowsheet
  ✔️ Stream table
   . . . . . . . . . . . . . . . . . . . .
   ✔️ Highlight streams

**Comment by sspoon** [comment]
So I like Dan's suggestion, but let's make the whole thing verb forward. Also, Dan and I discussed this, and we agreed that title case is more common for menus (although Dan think it's wrong). So, let's go with:

**View** 
✔️ Show Flowsheet 
✔️ Show Stream Table 
. . . . . . . . . . . . . . . . . . . . 
✔️ Highlight Streams

**Comment by ksbeattie** [comment]
I like @sspoon suggestion.  Other than that I'd approve this PR.

But wait, there's more....  try this:
- Uncheck all 3 in the View menu
- Hit refresh
- re-check all 3 in the View menu

The flowsheet is kinda gone, but comes back if you hit the zoom-to-fit button
And the Stream Table is all squished up.

(I know, I know - you _love_ me!)  I don't think this needs to be fixed in this PR, but this should probably be moved to a new issue or fixed in a new PR.

**Review by dangunter — APPROVED** [review]
LGTM

**Pull request merged**
