### PR TITLE
Even more pylint checks

### PR DESCRIPTION
**Pull request by andrewlee94**
## Summary/Motivation:
Fixes a lot more pylint issues and activates checks.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by dallan-keylogic** [comment]
I see a lot of disabling W0611 for "convenience imports", whatever that means.  We should either enforce this rule on ourselves or not enforce it on others.

**Comment by andrewlee94** [comment]
@dallan-keylogic Unfortunately that ends up breaking backward compatibility. Ideally we would fix them, but for now I want to make sure we don't start getting any more.

**Review by dallan-keylogic — APPROVED** [review]

**Review by lbianchi-lbl — CHANGES_REQUESTED** [review]
Just leaving this as a "Request changes" so that it doesn't automerge:

- We should remove the `v1-compat.yml` workflow file since that is already failing on `main` after #1111 (and causing unrelated PRs such as #1107 to fails as well)
- I'm starting to lose track of which checks are what using only the numeric code, so we should think of what would be the best way of using names instead. Probably just splitting the command in `.github/workflows/core.yml` using `\` would be the easiest

**Comment by andrewlee94** [comment]
@lbianchi-lbl Whilst I am using numeric codes for now, I how to eventually get this down to a short list where we can use names. However, numeric codes are a lot easier for me to work with when testing things, so I would prefer to stay with them for now (as an interim solution).

**Review by lbianchi-lbl — APPROVED** [review]

**Pull request merged**
