### PR TITLE
Update IDAES-EXT version

### PR DESCRIPTION
**Pull request by eslickj**
New version of IDAES-EXT with these changes

- A function was added to calculate x/(exp(x) - 1), which deals with x = 0, by using a Taylor series expansion near x = 0.
- Isothermal compressibility and fugacity coefficient functions were added to the Helmholtz EoS functions
- PETSc (https://petsc.org/release/) was updated to 3.19.2

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by dallan-keylogic — APPROVED** [review]

**Review by dallan-keylogic — APPROVED** [review]

**Review by andrewlee94 — APPROVED** [review]
Not sure why these only showed up now, but there are some spelling errors causing the tests to fail.

**Comment by dallan-keylogic** [comment]
Most of those "spelling errors" are Github's spelling checker mistaking abbreviations like "equil" for "equal".

**Comment by lbianchi-lbl** [comment]
@bpaul4 one precaution to ensure that the updates are correctly picked up in the environment would be to run e.g. `pip uninstall --yes idaes-pse && pip install . && idaes get-extensions --verbose` before running the tests, and verify that v3.4.0 is shown. I see that you mention updating the extensions but still seeing v3.3.0, so this could be worth a try if you haven't already.

For reference, this is the output of `idaes get-extensions --verbose` on one of the Windows CI runs:

```txt
   Getting files...
  DEBUG   idaes.commands.util.download_bin: Downloading binaries for windows-x86_64
  DEBUG   idaes.commands.util.download_bin: Downloading binaries from https://github.com/IDAES/idaes-ext/releases/download/3.4.0
  DEBUG   idaes.commands.util.download_bin: Getting checksum file https://raw.githubusercontent.com/IDAES/idaes-ext/main/releases/sha256sum_3.4.0.txt
  DEBUG   idaes.commands.util.download_bin: Getting petsc from: https://github.com/IDAES/idaes-ext/releases/download/3.4.0/idaes-petsc-windows-x86_64.tar.gz
  DEBUG   idaes.commands.util.download_bin: Saving solvers to: C:\Users\runneradmin\AppData\Local\idaes\bin\idaes-petsc-windows-x86_64.tar.gz
  DEBUG   idaes.commands.util.download_bin: Getting lib from: https://github.com/IDAES/idaes-ext/releases/download/3.4.0/idaes-lib-windows-x86_64.tar.gz
  DEBUG   idaes.commands.util.download_bin: Saving solvers to: C:\Users\runneradmin\AppData\Local\idaes\bin\idaes-lib-windows-x86_64.tar.gz
  DEBUG   idaes.commands.util.download_bin: Getting solvers from: https://github.com/IDAES/idaes-ext/releases/download/3.4.0/idaes-solvers-windows-x86_64.tar.gz
  DEBUG   idaes.commands.util.download_bin: Saving solvers to: C:\Users\runneradmin\AppData\Local\idaes\bin\idaes-solvers-windows-x86_64.tar.gz
  DEBUG   idaes.commands.util.download_bin: petsc Hash 5902d8fd766f290530dadd5086a853248119e826fa99b610ee01ae8decf84e85
  DEBUG   idaes.commands.util.download_bin: lib Hash 183fe5ba8022cc0d25ad0af40355b6a84e49cbf5845664576329d09b04e6f803
  DEBUG   idaes.commands.util.download_bin: solvers Hash b8f8b229f6cce6d8c657b0136f32b3a3415b664371d3bf61c1f2ce780419280d
  DEBUG   idaes.commands.util.download_bin: Extracting files in C:\Users\runneradmin\AppData\Local\idaes\bin\idaes-petsc-windows-x86_64.tar.gz to C:\Users\runneradmin\AppData\Local\idaes\bin
  DEBUG   idaes.commands.util.download_bin: Extracting files in C:\Users\runneradmin\AppData\Local\idaes\bin\idaes-lib-windows-x86_64.tar.gz to C:\Users\runneradmin\AppData\Local\idaes\bin
  DEBUG   idaes.commands.util.download_bin: Extracting files in C:\Users\runneradmin\AppData\Local\idaes\bin\idaes-solvers-windows-x86_64.tar.gz to C:\Users\runneradmin\AppData\Local\idaes\bin
  Done
  ---------------------------------------------------
  IDAES Extensions Build Versions
  ===================================================
  Solvers:  v3.4.0 20230607-2153 windows-x86_64
  Library:  v3.4.0 20230607-2236 windows-x86_64
  ===================================================
```

**Comment by eslickj** [comment]
I took a look at this and I see the error.  Here's more details.  This is in "step 3 generate performance results cell".  The solve with PETSc goes fine and a bunch of plots are generated, so PETS is mostly working and apparently able to get the trajectory data.  I did update the PETSc version here, so I'll have to assume that that's reason for this failure.

```
--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[31], line 4
      1 ###########################################################################
      2 #  Heat requirements
      3 ###########################################################################
----> 4 heat_computation(m, tj_ads, tj_des, adsorption_temperature, desorption_temperature)

File ~/git/examples/idaes_examples/mod/co2_adsorption_desorption/simulation_utilities.py:102, in heat_computation(m, tj_ads, tj_des, adsorption_temperature, desorption_temperature)
     98 ###########################################################################
     99 #  Heating duty required during desorption
    100 ###########################################################################
    101 solid_phase = m.fs_des.FB.config.solid_phase_config
--> 102 m.fs_des.FB.time_set = ContinuousSet(
    103     initialize=tj_des.time,
    104     doc="time domain",
    105 )
    106 time_elements_des = m.fs_des.FB.time_set.get_finite_elements()
    107 tf_des = m.fs_des.FB.time_set.last()

File ~/miniconda3/envs/idaes/lib/python3.11/site-packages/pyomo/core/base/block.py:580, in _BlockData.__setattr__(self, name, val)
    575 if name not in self.__dict__:
    576     if isinstance(val, Component):
    577         #
    578         # Pyomo components are added with the add_component method.
    579         #
--> 580         self.add_component(name, val)
    581     else:
    582         #
    583         # Other Python objects are added with the standard __setattr__
    584         # method.
    585         #
    586         super(_BlockData, self).__setattr__(name, val)

File ~/miniconda3/envs/idaes/lib/python3.11/site-packages/pyomo/core/base/block.py:1185, in _BlockData.add_component(self, name, val)
   1177     logger.debug(
   1178         "Constructing %s '%s' on %s from data=%s",
   1179         val.__class__.__name__,
   (...)
   1182         str(data),
   1183     )
   1184 try:
-> 1185     val.construct(data)
   1186 except:
   1187     err = sys.exc_info()[1]

File ~/miniconda3/envs/idaes/lib/python3.11/site-packages/pyomo/dae/contset.py:253, in ContinuousSet.construct(self, values)
    245     raise ValueError(
    246         "ContinuousSet '%s' must have at least two values"
    247         " indicating the range over which a differential "
    248         "equation is to be discretized" % self.name
    249     )
    251 if len(self) < 2:
    252     # (reachable if lb==ub)
--> 253     raise ValueError(
    254         "ContinuousSet '%s' must have at least two values"
    255         " indicating the range over which a differential "
    256         "equation is to be discretized" % self.name
    257     )
    258 self._fe = list(self)
    259 timer.report()

ValueError: ContinuousSet 'fs_des.FB.time_set' must have at least two values indicating the range over which a differential equation is to be discretized
```

**Comment by eslickj** [comment]
Okay, looking into it further, what seems to be happening is that the problem is that the desorption part of the model is failing to solve with the newer version of PETSc.  The adsorbtion part seems fine.  The initial conditions for desorb solve failes.  Hers the tail.  After the initial conditions solve fails, unsurprisingly, the DAE solve fails.

```
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: 385 SNES Function norm 1.008837504694e-04 
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: 386 SNES Function norm 9.935690494004e-05 
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: 387 SNES Function norm 9.841922815984e-05 
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: 388 SNES Function norm 9.795600322864e-05 
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: 389 SNES Function norm 9.471686711987e-05 
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: 390 SNES Function norm 9.445765631018e-05 
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: 391 SNES Function norm 9.265249633956e-05 
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: 392 SNES Function norm 9.057626981127e-05 
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: SNESConvergedReason = SNES_DIVERGED_LINE_SEARCH, in 392 iterations
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: SNES_DIVERGED_LINE_SEARCH
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: WARNING: Loading a SolverResults object with a warning status into
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae: model.name="ScalarBlock";
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae:     - termination condition: unbounded
2023-06-20 13:20:43 [INFO] idaes.solve.petsc-dae:     - message from solver: SNES_DIVERGED_LINE_SEARCH
```

**Comment by eslickj** [comment]
@bpaul4 and @andrewlee94, I spent some time on this.   It looks like Chinedu's work, so I'm not sure who should work on fixing this.  The issue is that the initial condition solve step for desorbtion fails.  I tried different solver options for pets and I tried replacing PETSc with ipopt with ma57 and ma57 scaling.  That also failed.  I guess we must have just been getting super lucky before.  I'm not sure what is needed to fix this, but assuming the problem is well posed, my feeling is that we need a better initial guess on the initial conditions in the description part.

Maybe to save somebody some time, to debug this and see solver output, to the cell titled "Setup PETSc integrator and simulate desorption step,"  add the code (the notebook is set up to hide solver output):

```
petscsolvelog = idaeslog.getSolveLogger("petsc-dae")
petscsolvelog.setLevel(logging.DEBUG)
```

**Pull request merged**
