### PR TITLE
Adding support for Henry's Law components

### LINKED ISSUE #369: Support for Henry's Law in generic property framework
It would be useful to include an option in the generic property framework to support Henry's Law for gases present in liquid mixtures at equilibrium. This also includes an extension to the existing initialization routine for bubble and dew point temperatures, to account for such systems, and model the VLE accordingly.

### PR DESCRIPTION
**Pull request by andrewlee94**
## Summary/Motivation:
This PR adds code necessary to support Henry's Law components to the generic property framework. For now, we only support the form `yP=xH`, but other forms could potentially be added.

## Changes proposed in this PR:
- Class for calculating Henry's constant (currently only includes constant value)
- Configuration argument for indicating phases in which a component follows Henry's Law
- Logic to support switching between Raoult's and Henry's Laws when calculating fugacity
- Support for calculating bubble and dew points with Henry components, including routines for initialisation.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by Andresj89 — APPROVED** [review]
LGTM

**Comment by andrewlee94** [comment]
@anujad95 Any update on how testing of this went?

**Review by anujad95 — DISMISSED** [review]
LGTM

**Comment by andrewlee94** [comment]
@anujad95 @Andresj89 Could you re-review this please? I had an `asset False` left behind in a test that had to be removed.

**Review by Andresj89 — APPROVED** [review]
LGTM

**Review by anujad95 — APPROVED** [review]
LGTM

**Pull request merged**
