### PR TITLE
Update imports of `native_types` and `pyomo_constant_types` in scaling module

### PR DESCRIPTION
**Pull request by Robbybp**
These should be imported from `pyomo.common.numeric_types`. Also, `pyomo_constant_types` was deprecated last week (although I don't do anything about that). This PR is necessary to prevent import errors with pyomo/main, as `pyomo_constant_types` no longer exists in `pyomo.core.expr.numvalue`.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — APPROVED** [review]
Looks good to me.

**Review by dallan-keylogic — APPROVED** [review]
Looks good to me. If `pyomo_constant_types` is deprecated, we probably should open an issue to move away from using it eventually.

**Comment by jsiirola** [comment]
I would also recomment changing the following line (and removing the import of `pyomo_constant_types`):
```diff
diff --git a/idaes/core/util/scaling.py b/idaes/core/util/scaling.py
index d4bd825..f3ee1cf 100644
--- a/idaes/core/util/scaling.py
+++ b/idaes/core/util/scaling.py
@@ -1509,7 +1509,7 @@ class NominalValueExtractionVisitor(EXPR.StreamBasedExpressionVisitor):
         # first check if the node is a leaf
         nodetype = type(node)

-        if nodetype in native_types or nodetype in pyomo_constant_types:
+        if nodetype in native_types:
             return [node]

         node_func = self.node_type_method_map.get(nodetype, None)
```

**Comment by andrewlee94** [comment]
@Robbybp Would you be able to add the addition change @jsiirola suggested?

**Pull request merged**
