### PR TITLE
Stream table brushing

### PR DESCRIPTION
**Pull request by elbashandy**
## Summary/Motivation:
Potential user showed interest in marking links when they hover over streams in the stream table and vice versa.

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ksbeattie** [comment]
Two minor suggestions:
1. Add the ability to turn this feature on/off.  Maybe via the "View" menu.  Not sure if the default should be on as it might be disorienting if the user hasn't enabled it.
2. When the table column is highlighted and text within each cell moves a little bit.  Anyway to prevent that movement?

**Review by dangunter — APPROVED** [review]
Looks good

**Review by ksbeattie — DISMISSED** [review]
LGTM

**Review by dangunter — APPROVED** [review]
Looks good

**Pull request merged**
