### PR TITLE
Update Sphinx theme to address unordered list spacing issues

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Summary/Motivation:

The list of collaborating institutions on the IDAES docs index page should be rendered as a bulleted list in HTML, but currently isn't:

image

This PR fixes this:

image

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ksbeattie** [comment]
Wow, removing the entire file, seemed to work!

**Comment by lbianchi-lbl** [comment]
> Wow, removing the entire file, seemed to work!

Yeah, it looks like there was a `theme.css` that appears to be taken from a previous version of `sphinx-rtd-theme` and copied to IDAES's own `docs/static` directory that (my guess) was probably interfering in some way with the corresponding file from the `pip install`ed version of the theme.

One hint pointing in this direction is that, in the HTML of the docs built without removing the extra CSS file, `theme.css` is included twice:

image

This could also potentially explain the different behavior between local builds and RTD since the mechanism for copying and including CSS files might differ between the two.

From a very cursory glance, removing `theme.css` seems to address the issue without breaking anything else, but we should probably check to make sure that we're not missing the reason why the file was there in the first place (https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence). Maybe @dangunter can shed some light on this?

**Review by FiannaOBrien — APPROVED** [review]
Great work sussing it out!

**Review by ksbeattie — APPROVED** [review]
LGTM

**Pull request merged**
