### PR TITLE
Function Scoping Fixes

### PR DESCRIPTION
**Pull request by dallan-keylogic**
## Fixes
-- Fixes function closure issues outlined in #1240 and #1241 for the Separator and SOC.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by andrewlee94** [comment]
@jsiirola Would you have time to take a quick look at this to double check that there aren't any other unexpected issues related to this (either ones that were already there or something added by this change)?

**Review by andrewlee94 — APPROVED** [review]
This looks good to me, pending the tests passing.

**Comment by dallan-keylogic** [comment]
@andrewlee94 , I renamed some variables, which seems to have triggered CodeCov. Is there a way to just force the rest of the checks to run anyway?

**Comment by andrewlee94** [comment]
@dallan-keylogic It looks like the CodeCov failure is due to coverage creep in the repo - our threshold for coverage is slowly creeping up as we force better coverage in the codebase which means that older sections can fall below the new threshold. In this case I am happy to bypass that check.

**Review by bpaul4 — APPROVED** [review]
This looks good to me. Interesting idea placing repeated exceptions in callable methods, too.

**Comment by dallan-keylogic** [comment]
> This looks good to me. Interesting idea placing repeated exceptions in callable methods, too.

If I have to copy and paste once I cringe, if I have to do it twice it becomes a method. That way if you want to change something, you only need to change it one place rather than ten different places scattered throughout the code.

**Pull request merged**
