### PR TITLE
Column model and MEA property corrections

### PR DESCRIPTION
**Pull request by anujad95**
## Fixes
Corrections to the vapor holdup expression, control volume area constraints in the column model, and molar flow upper bound in the MEA property package.

## Summary/Motivation:
Improving the generic column model and MEA property package with minor corrections.

## Changes proposed in this PR:
Column model
-  Volumetric vapor holdup expression changed according to valid index points
-  Vapor and liquid phase cross sectional area constraints defined at the respective inlets

MEA solvent and vapor property package
- Increasing upper bound for molar flows

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — APPROVED** [review]
Looks good.

**Comment by andrewlee94** [comment]
@anujad95 Unsurprisingly, the changes you made affected the results of the model (albeit slightly), but that means the tests are now failing. Please make sure to run the tests for any code you are working on before commiting to avoid failed runs like this.

**Comment by andrewlee94** [comment]
@anujad95 The change you made does not appear to have fixed the issue with the tests- note that there are three test failures and one of them is a failure to solve.

**Review by aostace01 — APPROVED** [review]
Looks good.

**Pull request merged**
