### PR TITLE
Fixing bug in usage of config arguments in CSTR model

### PR DESCRIPTION
**Pull request by andrewlee94**
**NOTE:** When this PR is approved, you *must* do the following so it can be merged:
* Add the "approved" tag to the pull-request
* Trigger tests by pushing a commit or manually re-running in CircleCI

See [this wiki page](https://github.com/IDAES/idaes-dev/wiki/Github-Pull-Request-Workflow-with-Approval-Tag) for details.

----
## Summary/Motivation:
A bug was found where the wrong argument from the config block was being used in creating the material balance constraints for the CSTR model (affected cases with chemical equilibrium).

## Changes proposed in this PR:
- Corrects configuration argument used.
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

----

## Reviewer Checklist
* Reviewer 1
- [ ] Tests: do they pass, do they cover functionality, are they understandable?
- [ ] Documentation: is the code commented, are there user-level docs where needed?
* Reviewer 2
- [ ] Tests: do they pass, do they cover functionality, are they understandable?
- [ ] Documentation: is the code commented, are there user-level docs where needed?

### CODE REVIEW

**Review by eslickj — DISMISSED** [review]

**Review by jghouse88 — DISMISSED** [review]
LGTM

**Comment by ksbeattie** [comment]
I tried switching this to merge to `main` not `old_main` and it produced a ton of changes.  @andrewlee94, I'm thinking you need to rebase or re-create this branch/PR.

**Comment by andrewlee94** [comment]
@ksbeattie What is `old_main`? When this was created, it was branched off the then-current `idaes-pse/main`.

**Comment by andrewlee94** [comment]
@ksbeattie I updated my working branch by merging the latest `main` and then switched the base branch for this PR, and it looks OK to me now.

**Review by eslickj — COMMENTED** [review]
Looks good.

**Comment by lbianchi-lbl** [comment]
@andrewlee94 @ksbeattie Merging the `main` branch works, but this (once this PR is merged into `main`) would also "import" all the commits from `old_main`, i.e. the "idaes-dev as of abcde" commits that used to be `idaes-pse`'s `master` branch under the dual repo regime, into the current `main` branch (i.e. the "real" full Git history of the repo). I'm not sure of all the implications of this, but I feel sounds like something we should try to avoid if possible.

If we want to avoid that, it's enough to rebase/cherry pick these changes onto a new feature branch created from the current `main`. I've already tried this on a local clone of @andrewlee94's fork, with a branch that I named `cstr_bug_fix_cherrypicked_from_main` to avoid conflict/ambiguities. If you're OK with this, I could push this branch to `origin` (i.e. `https://github.com/andrewlee94/idaes-pse`), and then you should be able to use that branch to reopen this PR with no conflicts and no "crossing of the (commit) streams".

Alternatively, to avoid re-creating the PR, one could probably also force-push to this branch. This should be possible, but I'd have to look into this in more detail to be 100% sure of how GitHub will behave in this case).

**Comment by andrewlee94** [comment]
@lbianchi-lbl Given this is a one line fix, it is probably easier to just open an new PR. That said, this probably indicates that I should be careful with my other working branch, as it might have the same issues.

**Comment by lbianchi-lbl** [comment]
@andrewlee94 makes sense. For reference, a quick-n-dirty way of checking if the branch has the "right" history is to run `git log --oneline | grep 'idaes-dev as of' | wc -l` and verify that the output is 0.

**Pull request closed without merging**
