### PR TITLE
Bump the Pyomo tag to the Pyomo 6.3 release

### PR DESCRIPTION
**Pull request by blnicho**
## Summary/Motivation:
Bump the Pyomo tag to the 6.3.0 release.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by lbianchi-lbl — APPROVED** [review]
Thanks @blnicho!

**Review by jsiirola — APPROVED** [review]

**Review by andrewlee94 — APPROVED** [review]
Mostly a rubber stamp, but I don't see any issues.

**Comment by lbianchi-lbl** [comment]
It seems there is an error in one of the parameter estimation notebooks:

```log
2022-02-24 16:25:39,092 INFO - [Worker 0] Running notebook: econ_parmest.ipynb
2022-02-24 16:25:44,088 ERROR - [Worker 0] Notebook execution failed: execution error for '/tmp/tmpm056a4nw/econ_parmest.ipynb': An error occurred while executing the following cell:
------------------
import pyomo.contrib.parmest.parmest as parmest
import numpy as np

parmest_results={}
# run parmest tool for each power bin
for i, group in df.groupby("bin_no"):
    pest = parmest.Estimator(get_model, list(group.index), theta_names, sse)
    obj, theta = pest.theta_est()
    print(f"Bin number: {i},  objective: {obj}")
    print(theta)
    parmest_results[i] = {'obj':obj, 'theta': theta}
------------------

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_3147/2251773996.py in <module>
      5 # run parmest tool for each power bin
      6 for i, group in df.groupby("bin_no"):
----> 7     pest = parmest.Estimator(get_model, list(group.index), theta_names, sse)
      8     obj, theta = pest.theta_est()
      9     print(f"Bin number: {i},  objective: {obj}")

/usr/share/miniconda/envs/idaes-pse-dev/lib/python3.7/site-packages/pyomo/contrib/parmest/parmest.py in __init__(self, model_function, data, theta_names, obj_function, tee, diagnostic_mode, solver_options)
    308         else:
    309             self.callback_data = data
--> 310         assert isinstance(self.callback_data[0], (dict, pd.DataFrame, str)), "The scenarios in data must be a dictionary, DataFrame or filename"
    311 
    312         if len(theta_names) == 0:

AssertionError: The scenarios in data must be a dictionary, DataFrame or filename
```

**Comment by lbianchi-lbl** [comment]
To break the chicken-and-egg impasse between this and IDAES/examples-pse#102, I'll go ahead and merge this in, even though the "Run examples" check is failing. Once IDAES/examples-pse#102 is merged in, all CI checks will then be expected to succeed.

**Pull request merged**
