### PR TITLE
Tracking updates to pyomo units handling

### PR DESCRIPTION
**Pull request by jsiirola**
## Summary/Motivation:
Recent Pyomo updates to improve general units performance also changed some of the user-facing experience (the string representation operator spacing now matches the one used for Pyomo expressions, and some of the exception messages are more informative).  This PR tracks those changes and will be needed when we bump the IDAES branch that we test against.

This also corrects the call to verify units in `test_reaction_example.py`

NOTE: tests will not pass until the IDAES branch is bumped to the current Pyomo master

## Changes proposed in this PR:
- Update expected strings from pyomo units (strings and verification)
- Correct call to verify units on the reaction example

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — DISMISSED** [review]
Looks good to me. I wonder how "test_reaction_example.py" worked before however.

**Comment by jsiirola** [comment]
@andrewlee94: Me too...

**Review by jghouse88 — DISMISSED** [review]
LGTM

**Comment by jghouse88** [comment]
@jsiirola I am don't see the fix to the drum model from @eslickj though.

**Comment by jsiirola** [comment]
@jghouse88 It was a PR to this PR.  I went ahead and merged it (which dismissed your review).

**Review by jghouse88 — APPROVED** [review]
LGTM

**Review by blnicho — APPROVED** [review]

**Pull request merged**
