### PR TITLE
Cleaning unit model mappings

### PR DESCRIPTION
**Pull request by elbashandy**
## Fixes

- Changing the current default to a smaller solid square
- Added more mappings to cover the Turbine/Expander unit models
- Added mappings to cover more unit models

## Summary/Motivation:
Based on [the USC dispatches model](https://raw.githubusercontent.com/nareshsusarla/dispatches/usc_storage/dispatches/models/fossil_case/ultra_supercritical_plant/storage/pfd_usc_charge_2-5disj_helm_updated_oil_mod_source_disj.svg) that was provided by Soraya, these changes make the visualization more visually comprehensible

This changes the model from this:
Screen Shot 2022-02-07 at 4 49 09 PM

To this:
Screen Shot 2022-02-10 at 1 15 25 PM

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by dangunter — CHANGES_REQUESTED** [review]
Add keys instead of wildcarding for multiple names mapping to same unit symbol

**Comment by sspoon** [comment]
AR and I discussed the default icon on Slack, and it looks good as a placeholder

**Review by dangunter — DISMISSED** [review]
Lookin' good in the neighborhood.

**Review by sspoon — APPROVED** [review]
I approve the changes to the default icon

**Pull request merged**
