### PR TITLE
Add option to change the initial condition solver.

### PR DESCRIPTION
**Pull request by eslickj**
## Summary/Motivation:

This adds an option to use a different nonlinear solver for the initial condition solving step.  This is motivated by the failures in https://github.com/IDAES/idaes-pse/pull/1199, but it doesn't solve the issue.  It provides more options for potentially addressing or debugging it. 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — APPROVED** [review]
Looks OK to me - my only question is if there is something that should be updated in the docs about this (beyond just the doc string).

**Comment by eslickj** [comment]
@andrewlee94, I looked at the docs, and I think the only update needed is the docstring.

**Review by bpaul4 — APPROVED** [review]

**Comment by eslickj** [comment]
@lbianchi-lbl or @andrewlee94, it looks like the example tests are failing, but as far as I can tell it is unrelated to this PR.

**Comment by bpaul4** [comment]
@eslickj yes, the failures appear unrelated. I opened an issue in #1215.

**Pull request merged**
