### PR TITLE
Fix mixer and spe scale when components not in a phase

### PR DESCRIPTION
**Pull request by eslickj**
## Fixes
An issue with mixer and separator scaling when components are not in a phase.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by chineduobiora — APPROVED** [review]
Looks good to me.

**Comment by andrewlee94** [comment]
@eslickj Do you have a case where this was a problem that I can look at? I cannot see how this became a problem as all the balance equations should be indexed by the phase-component set, thus only valid phase-component pairs should be appearing.

**Comment by eslickj** [comment]
@andrewlee94, I don't have a good example handy.  I changed the model where I originally observed the problem.  It was using the  generic property package with the parameter dict from https://github.com/IDAES/idaes-pse/blob/main/idaes/power_generation/properties/natural_gas_PR.py.  As it is now only water can be liquid.  So I had H2 and water and saw this.  I'll tak a look at the mass balance, but I assumed since I saw this, probably used Constraint.skip in there.

**Comment by eslickj** [comment]
@andrewlee94, after looking into this more. I found and unneeded "if" with an unused constraint skip in Mixer.  That's not the problem though.  The problem is that calculate scale factors iterates through the constraint, and inside that iterates through the phases, when really the phase index is part of the constraint index.  So while I guess this fix works,  it's probably not the right fix, which would be to fix the loop.

**Comment by andrewlee94** [comment]
@eslickj I think I see the problem now. In the Mixer at least, there is an issue when doing a total component balance approach (lines 1010-1013). I think the other branches should be fine with out the `try/except` however as they are already iterating over the phase-component set and so should exclude any infeasible phase-component combinations.

For the total component basis, we could alternatively use and `if` to handle the issue:

```
for i, p in enumerate(self.mixed_state.phase_list):
    if (p, j) not in self.mixed_state.phase_component_set:
        continue
```

The `try/except` for might be faster however, as we can generally assume most phase-component pairs exist.

**Pull request merged**
