### PR TITLE
Fix execute on load with uncertainty_propagation examples

### LINKED ISSUE #332: Uncertainty example runs code on import
One of the examples for the uncertainty propagation tools runs code on import:

idaes/apps/uncertainty_propagation/examples/simple_opt_problem.py

This causes the IDAES imports test (idaes/tests/test_import.py) to fail.

Additionally, some of the test for uncertainty propagation lack pytest marks.

### PR DESCRIPTION
**Pull request by adowling2**
## Changes proposed in this PR:
- Add missing `if __name__ == "__main__":` in `uncertainty_propagation` examples

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by andrewlee94** [comment]
I think this addresses the main concern. However, it crossed my mind that we should probably have tests for these as well - at least something to make sure that they run and given the expected final result.

**Comment by lbianchi-lbl** [comment]
> I think this addresses the main concern. However, it crossed my mind that we should probably have tests for these as well - at least something to make sure that they run and given the expected final result.

I agree with @andrewlee94 on both points. One solution for this would be to move the code to a `main()` function, and then call it in the `if __name__  ...` block:

```py
from idaes import foo, bar

def main():
    # all code goes here

if __name__ == '__main__':
    main()
```

Then tests would be able to do `from idaes.mymodule import main()` and call it (at the most basic level, checking that no exceptions are raised).

**Comment by ksbeattie** [comment]
> > I think this addresses the main concern. However, it crossed my mind that we should probably have tests for these as well - at least something to make sure that they run and given the expected final result.
> 
> I agree with @andrewlee94 on both points. One solution for this would be to move the code to a `main()` function, and then call it in the `if __name__ ...` block:
> 
> ```python
> from idaes import foo, bar
> 
> def main():
>     # all code goes here
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> Then tests would be able to do `from idaes.mymodule import main` and call it (at the most basic level, checking that no exceptions are raised).

Is there any reason why this code that would be in `main()` should not just be moved into a separate test file?

**Review by ksbeattie — APPROVED** [review]
I'm approving this, even though I think the executable code here would better done as a test or as an example.  Hopefully that will be done?

**Review by andrewlee94 — APPROVED** [review]

**Comment by adowling2** [comment]
@ksbeattie @andrewlee94 This is in examples mainly because it is intended as the first example for a new user to look at. It is the simple math problem in the documentation.

**Comment by andrewlee94** [comment]
@adowling2 Our main comment here is that these end up buried in the code, and not easily found by users. They would be better put in the docs, or examples-pse repo as notebooks, so that users could easily find them.

That said, they also serve as useful test cases for the test suite, and we should make sure they are included there as well.

**Pull request merged**
