### PR TITLE
Add more debug logging to solver download.

### PR DESCRIPTION
**Pull request by eslickj**
## Changes proposed in this PR:
 Add some extra debug logging to diagnose issue #236.  Now it you use the --verbose flag you'll see what we think the Linux distro is.  My guess with issue #236 is that we will see that it included something about WSL.   

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — APPROVED** [review]
Looks OK to me.

**Comment by dangunter** [comment]
I think it would be safer to print out a list of known distributions and stop instead of assuming a default and continuing. To support the workflow where an expert user knows the right one, an option like `--os=<name>" can be added, so they can pick one of the values from the list. After listing out possible values, the error message could include a hint like "If you know that your OS and distribution is equivalent to one of the ones listed, use the '--os=<name>' option to choose the appropriate name and avoid this check."

**Review by dangunter — CHANGES_REQUESTED** [review]
See comment re: setting OS explicitly.

**Comment by eslickj** [comment]
@dangunter and @andrewlee94, updated it, now if a supported platform isn't detected it raises and exception and prompts you to specify one.  It also tells you what was detected so like if it detects ubuntuWSL.18.04 or something weird you know what happened.

Here's and example of asking for "linux" on Windows 10 (seems a little silly because I detect the linux distro as win10 so maybe I should just get windows anyway, but I did say I wanted linux, anyway you get the idea):

```sh
(idaes-pse) C:\Users\EslickJ\git\idaes-pse\idaes\generic_models\properties\core\generic>idaes get-extensions --platform linux --verbose
Getting files... 
2021-03-22 21:18:32 [DEBUG] idaes.util.download_bin: Detected Linux distribution: win10                                                                                                                                                                                                                                                 

Detected platform win10 is not recognized as supported platform.                                                                                                                                                                                                                                                                        

Specify one of the following platforms with --platform <os>:
  auto
  centos6
  centos7
  centos8                                                                                                                                                             
  darwin
  rhel6                                                                                                                                                               
  rhel7
  rhel8                                                                                                                                                               
  ubuntu1804
  ubuntu1910                                                                                                                                                          
  ubuntu2004
  windows                                                                                                                                                                                 
```

**Review by jsiirola — DISMISSED** [review]

**Comment by eslickj** [comment]
@dangunter, could you take another look at this?

**Comment by dangunter** [comment]
@eslickj I think it is good except one minor comment. You added a new command "get-extensions-platforms", but wouldn't it be simpler to just print out the platforms (and stop) if the user gives the "--platforms" option (with an s)?

```
idaes get-extensions --platform foobar  # prints out 'Unknown platform: foobar' and then lists available
idaes get-extensions --platforms # prints out nothing and lists available
```

This would require changes like:
```
@click.option(
    "--platform",
    help="Platform to download binaries for. Use '--platforms'"
         " for a list of available platforms (default=auto)",
    default="auto")
@click.option(
    "--platforms", help="List available platforms for --platform argument",
    is_flag=True)
```

and then add "platforms" to the function args, and refactor the list-platforms function:
```
def _list_platforms(platform=None):
    click.echo(
        "Specify one of the following platforms with --platform <os>:")
    for i in sorted(idaes.config.known_binary_platform):
        if i == platform:
            # auto or linux specified, and it didn't work.
            # will need to be more specific.
            continue
        click.echo(f"  {i}")
```

and add at the top of the function logic like:

```
 if platforms:
        _list_platforms()
        return
```
and, obviously, call _list_platforms() also if there is an UnsupportedPlatformError

**Comment by eslickj** [comment]
@dangunter, unfortunately I have several commands like that, and I agree with you about how they should have been done.  I think about updating them every month or so then let it go.  I guess since you brought it up.  It's a good time to make some updates.

**Review by dangunter — DISMISSED** [review]
I'm sure it's good now.

**Review by jsiirola — APPROVED** [review]

**Review by dangunter — APPROVED** [review]
Looks good

**Pull request merged**
