### PR TITLE
Clean up of Packed Column Models

### LINKED ISSUE #244: MEA model TODO list
Tracking TODOs from PR #140 and feature branch solvent_column:

- [ ] Tests need to be standardized.
    - [ ] Test marks are inconsistent
    - [ ] Need unit consistency checks
    - [ ] Check how pressure drop is handled. At one point, the initialization routine was changing the model state regarding pressure
    - [ ] Need to use initialization tester (this may depend on handling pressure above)
    - [ ] Need more verification checks (material and energy conservation, more asserts for model results)
    - [ ] Need more modular testing of build, initialization and solve steps
- [x] Rename `phe` model to `PlateHeatExchanger`
- [ ] Check for unit consistency and consider standardizing units. Property units are currently mixed (e.g. some using cm**3)
- [ ] Standardize naming of some variables - two I noted were `lnk_eq_conc` (consider if there is or should be a standard name) and `enth_liq_dens` (should be `enth_vol_liq`).
- [ ] Reaction package as a config argument and integrate with model
- [x] Remove reference to the time domain, and just make a local alias instead
- [x] More descriptive name for the var ` self.N_v`
- [ ] Create indexed vars for `yi`
- [x] Switch to using IDAES logger instead of Python `warnings` module
- [x] Change logger messages from all caps to normal
- [ ] Check vars fixed in the model (either convert to params or remove fixing in code) @andrewlee94 - I think I prefer `Vars` for most of these.
- [ ] Column pressure and options. The model currently provides config argument for options which do not exist. Also, column pressure is fixed via a config argument with a somewhat arbitrary default value.
- [ ] Review initialization routine. Logging should be standardized, and we should check if homotopy is required when using MA27 as the linear solver.
- [ ] Plate Heat Exchanger model directly references parameters from property package

Less Important:
- [ ] Consider whether plotting functions should live in a separate utility module
- [ ] Model report functions

### PR DESCRIPTION
**Pull request by andrewlee94**
## Summary/Motivation:
This PR cleans up the current solvent column models. The biggest change is dividing  the existing model into two parts - a simple generic column model and a more rigorous version for MEA capture.

Additionally, a number of things have been cleaned up such as units of measurement, scaling and removing some assumptions/requirements on the property package.

## Changes proposed in this PR:
- Remove old column model in `power_generation/carbon_capture`
- Add a new `mea_solvent_column` model in `power_generation/carbon_capture` which derived from the more general model in `generic_models/unit_models/column_models`
- Move most heat and mass transfer correlations from the generic model to the new `mea_solvent_column`
- Standardized handling of units of measurement and addressed some lingering unit consistency issues
- Removed requirement for liquids properties to define solvent and solute components
- Added additional tests to verify values of key variable for all test cases

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by andrewlee94** [comment]
@anujad95 @aostace01 Would you be able to test this PR with the MEA flowsheet/UQ example? I do not have access to those models so I wasn't able to test it against it. Note that you will need to to switch to using the new `MEAColumn` model in `power_plant/carbon_capture/mea_solvent_systems/unit_models/mea_solvent_column.py` instead of the one in `generic_models/unit_models` (I broke the model into two parts).

Additionally, a few things have changed in this PR. A number of config arguments were removed, and `vapor_side` became `vapor_phase` for consistency (same for the liquid). You will also see some small changes in the model results due to me trying to standardize some things - those changes were fairly minor for the test cases I can't guarantee that. You can hopefully see how to use the new version via the tests.

**Comment by aostace01** [comment]
I do not have access to those models either. @anujad95, can you please point me to them/share them with me?

**Comment by ksbeattie** [comment]
@anujad95, @aostace01, @MAZamarripa is there any progress on this?

**Comment by andrewlee94** [comment]
Closing this as things have moved to far since it was created.

**Pull request closed without merging**
