### PR TITLE
Pysmo expression generator fix for scalar pyomo variables

### PR DESCRIPTION
**Pull request by OOAmusat**
## Summary/Motivation:
PySMO's expression generator was originally designed to work with indexed Pyomo variables. This change allows the user to generate expressions with scalar variables as well

## Changes proposed in this PR:
- Extend PySMO's ``generate_expression`` function to scalar variable inputs

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by bpaul4** [comment]
@OOAmusat testing the new code on the example I'm developing, it appears this resolved this issue. I do believe it would be useful to add tests for PySMO and ALAMO for solving a flowsheet containing a SurrogateBlock(), as the Keras test module does. This would not necessarily be in this PR, if not I am ready to approve.

**Comment by OOAmusat** [comment]
> @OOAmusat testing the new code on the example I'm developing, it appears this resolved this issue. I do believe it would be useful to add tests for PySMO and ALAMO for solving a flowsheet containing a SurrogateBlock(), as the Keras test module does. This would not necessarily be in this PR, if not I am ready to approve.

@bpaul4 Yeah, that would be useful. ALAMO and PySMO both test the SurrogateBlock() is generated correctly, so attaching them to a flowsheet should be trivial.

I guess that for ALAMO and PySMO we can just have a saved surrogate loaded from a file onto a block, attach that to a flowsheet, solve and check for optimal termination/solutions.

**Review by bpaul4 — DISMISSED** [review]
I'm approving this as it resolves the issue passing scalar variable lists. Feel free to re-request my review if you push more updates here, thanks for implementing this!

**Review by dangunter — DISMISSED** [review]
Looks good (though maybe add a comment as to why)

**Comment by OOAmusat** [comment]
@bpaul4 @dangunter can you please re-approve this? I just added some comments to the new code for clarity.

**Review by bpaul4 — APPROVED** [review]

**Review by dangunter — APPROVED** [review]
Looks good

**Pull request merged**
