### PR TITLE
 add water gas shift reaction

### PR DESCRIPTION
**Pull request by Morgan88888888**
## Fixes
Add water gas shift reaction in the natural gas properties. 

## Summary/Motivation:
This reaction will be used in the SMR based hydrogen generation plant in the TTNEP project.

## Changes proposed in this PR:
-Add water gas shift reaction
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — CHANGES_REQUESTED** [review]
@Morgan88888888 We will need some tests and maybe some documentation for this. There also appear to be some formatting issues that need to be resolved.

**Comment by ksbeattie** [comment]
@Morgan88888888 will you be able to get this done in the next week?  Otherwise it won't make the May release.

**Comment by eslickj** [comment]
As far as I can tell there is no documentation at all for the NG property package, and no tests for the reactions at all (other than being used in testing models in other places).  As best I remember, this just provides dictionaries of parameters to the generic properties and reactions package.  The dictionary is configurable to select whether the EoS is ideal or cubic and what components and reactions are present.  So I think the documentation can point to the generic properties and explain the options for creating the parameter dictionaries.  @Morgan88888888, can you take car of this or do you need help?

We'll need to add a doc page here https://github.com/IDAES/idaes-pse/tree/main/docs/reference_guides/model_libraries/power_generation/properties, and add reaction tests to the existing test file https://github.com/IDAES/idaes-pse/blob/main/idaes/models_extra/power_generation/properties/tests/test_NG_PR.py.

**Comment by Morgan88888888** [comment]
> @Morgan88888888 will you be able to get this done in the next week? Otherwise it won't make the May release. And please show up to the dev call so we can talk about it.

I have a series of models need to be added, they are related with the hydrogen generation process in the TTNEP project. I can talk about it if there is a dev meeting on schedule tomorrow.

**Comment by Morgan88888888** [comment]
> As far as I can tell there is no documentation at all for the NG property package, and no tests for the reactions at all (other than being used in testing models in other places). As best I remember, this just provides dictionaries of parameters to the generic properties and reactions package. The dictionary is configurable to select whether the EoS is ideal or cubic and what components and reactions are present. So I think the documentation can point to the generic properties and explain the options for creating the parameter dictionaries. @Morgan88888888, can you take car of this or do you need help?
> 
> We'll need to add a doc page here https://github.com/IDAES/idaes-pse/tree/main/docs/reference_guides/model_libraries/power_generation/properties, and add reaction tests to the existing test file https://github.com/IDAES/idaes-pse/blob/main/idaes/models_extra/power_generation/properties/tests/test_NG_PR.py.

Yes, I will add them. I may have some quick questions for you.

**Comment by Morgan88888888** [comment]
> @Morgan88888888 We will need some tests and maybe some documentation for this. There also appear to be some formatting issues that need to be resolved.

The file is formatted. I will work with @eslickj to add test and documentation.

**Comment by ksbeattie** [comment]
@Morgan88888888 any news on this?  Possible for a Nov release?

**Comment by Morgan88888888** [comment]
> @Morgan88888888 any news on this? Possible for a Nov release?

Thank you for your question! It's in progress. Let's get in touch offline to discuss this further.

**Comment by ksbeattie** [comment]
@Morgan88888888, we're going to close this for now.  If/When you can make progress on this, feel free to re-open it.

**Pull request closed without merging**
