### PR TITLE
Add double loop (grid-integration) docs.

### PR DESCRIPTION
**Pull request by xiangao1**
## Summary/Motivation:
Add double loop (grid-integration) docs.

## Changes proposed in this PR:

* Initial commit: Add docs to the required location.

* Rename the title of the double loop index page. Remove indices and tables.

* Include double loop docs in reference guide index.

* Include double loop docs in the IDAES docs index.

* Increase the figure sizes.

* Reformat the introductions.

* Split the docs into different sections.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by adowling2** [comment]
@nicolepcortes should also review this

**Comment by adowling2** [comment]
@Xinhe-Chen should also review this

**Comment by xiangao1** [comment]
Hi @lbianchi-lbl , I have added the rst files to the locations as we discussed over Slack. Could you take a look at them? 

Hi @Xinhe-Chen @nicolepcortes @adowling2 , could you review the contents of the docs? 

Thank you!

**Review by lbianchi-lbl — COMMENTED** [review]
Looking at the RTD build from this PR (https://idaes-pse--823.org.readthedocs.build/en/823/reference_guides/apps/grid_integration/index.html), everything looks good to me. I noticed something in what I presume is auto-generated from the docstrings that looks a bit odd in the HTML:

image

**Review by nicolepcortes — DISMISSED** [review]
Looks good to me.

**Comment by Xinhe-Chen** [comment]
Looks good to me.

**Review by Xinhe-Chen — APPROVED** [review]
Looks good to me.

**Pull request merged**
