### PR TITLE
Fix separator scale factor calcs

### PR DESCRIPTION
**Pull request by eslickj**
## Fixes

This is a problem reported by @minhwvu.  The scaling factor calculation is broken for separators when the separator doesn't have it's own mixed state block.  Unfortunate, I think we should try to get the fix in this release if possible.   I added a test that demonstrates the problem then fixed it.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — APPROVED** [review]
It would probably be good to have explicit tests for the two cases, but this looks good.

**Comment by eslickj** [comment]
@andrewlee94, yeah probably should be part of the new testing standards, to make sure the scale factors work right.  Right now they probably have pretty minimal coverage.  Just where we incidentally use them.

**Comment by minhwvu** [comment]
Thanks @eslickj . The error was fixed when I did a test with my model.

**Comment by eslickj** [comment]
@andrewlee94, you were right again.  I should have tested both cases because I broke it the opposite way.  Should be fixed and added more tests.  Hopefully it works this time.

**Review by andrewlee94 — APPROVED** [review]
Looks good to me.

**Review by jghouse88 — APPROVED** [review]
LGTM

**Pull request merged**
