### PR TITLE
Updatedate get-extensions command, prep for OSX

### PR DESCRIPTION
**Pull request by eslickj**
## Changes proposed in this PR:
- Does not raise a specific objection to darwin platform
- New exception when the file is not available this works but still a bit ugly as the 404 error produce a bit of extra output
- Option to skip the checksum check
- Option to install the libraries only and skip the solvers.  Currently solvers is: Ipopt, Pynumero, and k_aug.  Libraries contains mostly Helmholtz and Cubic EoS external functions.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by eslickj** [comment]
Need to add a libraries only option to allow property libraries to be installed without the solver package.

**Comment by eslickj** [comment]
I added a test that basically just downloads and extracts the release to an alternate location.  Not sure it's the best idea, but hopefully it's better than nothing.  It would be nice if we could flag the test CI only.  Do we have a marker like that?

**Review by jsiirola — APPROVED** [review]

**Comment by eslickj** [comment]
I added a --no-download option, so I could test the commands without downloading or extracting anything.  The download and extract function is tested separate from for commands.  I'm trying to get my test coverage up to passing level.

**Comment by lbianchi-lbl** [comment]
@eslickj the integration tests are triggered as expected, but they end up failing almost immediately for some reason. As the error happens before the code is even checked out, I believe this is due to a bug or corner case in the CI workflow rather than something having to do with the code. I'm looking into it.

**Comment by eslickj** [comment]
@jsiirola, could you take another look at this?  Since you last approved I had to make some changes to get better test coverage.  I think the changes were to improve testing, and make this more amenable to future simple unit tests.

**Review by jsiirola — APPROVED** [review]

**Review by adowling2 — APPROVED** [review]
LGTM

**Comment by adowling2** [comment]
@lbianchi-lbl Is it possible to merge this tomorrow AM into master? We are going to test out the macOS compilation instructions. It will simplify the process if this is in master (don't need to add John's fork as a remote).

**Pull request merged**
