### PR TITLE
Update grid integration

### PR DESCRIPTION
**Pull request by dguittet**
## Fixes
- `idaes/apps/grid_integration/bidder.py`: bidder should not add the original (pmax, marginal_cost) point to each optimized bid curve, since the pmax is purposefully being modified by the bid optimization. Also, for RE with variable energy, the pmax is not fulfillable but is a function of time
- `idaes/apps/grid_integration/model_data.py`: add function that allows modifying any Prescient generator parameter via `**kwargs` input; also update enforcement of pmax in default production cost curve for above

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ksbeattie** [comment]
@dguittet when is this expected for IDAES?  It's too late for the Nov release, fyi.

**Comment by adowling2** [comment]
@dguittet Is it okay for this to get merged into IDAES in February?

**Comment by ksbeattie** [comment]
I've placed this on the Feb release board with normal priority, please speak up if that's incorrect.

**Review by bknueven — APPROVED** [review]
The code looks good.

I do wonder if we need to be doing something fundamentally different (it looks like we're adding another epicycle here), but that should be saved for a subsequent discussion and PR.

**Review by Xinhe-Chen — APPROVED** [review]
Looks good to me. Thank you, Darice.

**Comment by andrewlee94** [comment]
@dguittet Is this PR required for the February IDAES release? If so, we need to get the issue with test resolved - it looks like the diff cover of the changes is low, so we either need to add more tests or at least have an explanation of why it is OK.

**Comment by dguittet** [comment]
It should be merged. I'll add some tests today. Thanks for checking

**Pull request merged**
