### PR TITLE
Power plant costing update

### PR DESCRIPTION
**Pull request by AlexNoring**
## Summary/Motivation:
This brings in the updates made to the power plant costing library from the NGCC branch.

## Changes proposed in this PR:
- The addition of functions to build constraints for fixed and variable O&M costs
- The inclusion of custom dictionaries within the power_plant_costing.py file to make it easier to add new cost accounts
- The custom dictionaries have been used to add an account for CO2 capture equipment at a capture rate above 90%

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by andrewlee94** [comment]
At the risk of creating havoc, should we hold off on this until the new costing framework proposal has been settled and implemented? Otherwise, we are going to need to rework this once that is done.

**Comment by AlexNoring** [comment]
@eslickj what are your thoughts on that? Could you push the NGCC model without costing until the new costing framework is settled?

**Comment by eslickj** [comment]
I think we should go ahead with this, but if you guys want to hold off, I can finish the NGCC model release without costing.  @jghouse88 and @MAZamarripa, are you guys using costing or just the NGCC model?  At this point we can't delay too long.   I think I have to get the NGCC out by the end of March and at the rate things happen I won't make it.

**Comment by andrewlee94** [comment]
I will note that the new costing proposal is moving along fairly quickly, and we might have a prototype ready in the next few weeks.

**Comment by eslickj** [comment]
Ok, let's put a pin in this.  We'll see where we are in March.  If a new interface is ready, we'll use that.  If not we'll go with this.

**Comment by andrewlee94** [comment]
@eslickj I have no objection, but we do need to be aware that this will need to be updated before IDAES 2.0 as the current costing framework will be deprecated. That said, the changes should not be that significant (based on converting the general costing package).

**Review by eslickj — APPROVED** [review]

**Review by MAZamarripa — APPROVED** [review]
lgtm

**Pull request merged**
