### PR TITLE
Copying TGA_model branch from workspace to idaes-pse

### PR DESCRIPTION
**Pull request by bpaul4**
## Summary/Motivation:
- Adding TGA model files in workspace (branch TGA_model) to main idaes-pse (newly created branch TGA_model)
- 
## Changes proposed in this PR:
- From files in IDAES/workspace/tree/master/tasks/task-3/task-3.2/chemical_looping on branch TGA_model, created new branch TGA_model to place files in IDAES/idaes-pse/tree/TGA_model/idaes/gas_solid_contactors
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by andrewlee94** [comment]
@bpaul4 Is there a particular reason you wanted to create a branch for this on `idaes-pse`? We generally avoid creating branches on the main repo as they tend to accumulate. In most cases, we work from branches on our personal forks, unless we expect to do a lot of collaborative work.

**Comment by bpaul4** [comment]
@andrewlee94 I am working with @chineduobiora on updating the model files, and we had previously discussed moving the branch from workspace to the main repo. The files are significantly different between the `gas_contactors` subfolders in the main repo and the `chemical_looping` subfolders in the workspace, so I made a new branch before moving the files.

**Comment by chineduobiora** [comment]
@bpaul4, Andrew is correct. Our normal approach is to work off branches on our personal fork of idaes-pse until the code is ready for review, that includes tests and documentation.

In addition, I noticed that you are copying all the files from main/workspace. The only files I was expecting to be moved are located in the **TGA_model branch** of the workspace repo. These files are **(i)** the example TGA flowsheet file (workspace/tasks/task-3/task-3.2/chemical_looping/flowsheets/ dyn_TGA_example.py), and **(ii)** the TGA unit model (workspace/tasks/task-3/task-3.2/chemical_looping/unit_models/ fixed_bed_0D.py).
 
These things can be a bit convoluted when being done for the first time, and my apologies if I wasn’t clear about the steps. What’s your availability after 3PM ET today? We can have a meeting to walk through the steps.

**Comment by bpaul4** [comment]
I'm closing this pull request for now, and will submit another correctly when I am ready.

**Pull request closed without merging**
