### PR TITLE
Remove CircleCI configuration

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Summary/Motivation

Now that the GitHub Actions (GHA) CI checks are running and enforced, the CircleCI configuration is redundant and can be removed.

## Changes proposed in this PR:

- Remove `.circleci` directory

**NOTE**: This should probably be merged after #50 (or #50 should be closed without merging) to avoid potential conflicts.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

----

### CODE REVIEW

**Review by jghouse88 — APPROVED** [review]
LGTM

**Review by ksbeattie — APPROVED** [review]
LGTM

**Review by dangunter — COMMENTED** [review]
Yep, let's remove it.

**Review by dangunter — APPROVED** [review]
LGTM

**Pull request merged**
