### PR TITLE
Insert value() method to resolve Boolean assertion error

### PR DESCRIPTION
**Pull request by bpaul4**
## Fixes
- Adds value() method to resolve failing assertion tests

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — DISMISSED** [review]

**Review by dallan-keylogic — DISMISSED** [review]

**Comment by andrewlee94** [comment]
@bpaul4 It looks like there is a second issue here as well. It looks like these two cases are using `pytest.approx(a == b)` or `pytest.approx(a, b)`.

These should be replaced with `a == pytest.approx(b)` (with `value()` where appropriate).

**Comment by bpaul4** [comment]
The first test is straightforward and passes:

```
@pytest.mark.unit
def test_datetime_timestamp():
    ts = time.time()
    dt = datetime.datetime.fromtimestamp(ts)
    ts1 = util.datetime_timestamp(dt)
    assert value(ts1) == pytest.approx(value(ts), 0.000001)
```

The second test fails (is this the correct way to update this?):

```
for i in m.params.component_list:
        for j in m.params.component_list:
            assert value(m.props[1].PR_daij_dT[i,j]) == \
                                 pytest.approx(value((1-m.params.PR_kappa[i, j])
                                 * (m.props[1].PR_fw[j] 
                                 * sqrt(m.props[1].PR_a[i]
                                     *  m.params.get_component(j).temperature_crit
                                     / m.params.get_component(j).pressure_crit)
                                  + m.props[1].PR_fw[i]
                                  * sqrt(m.props[1].PR_a[j]
                                      * m.params.get_component(i).temperature_crit
                                      / m.params.get_component(i).pressure_crit))))
```

`FAILED test_ceos_PR.py::test_common - AssertionError: assert -0.005903679876332056 == 0.03637534575014918 ± 3.6e-08`

**Comment by andrewlee94** [comment]
@bpaul4 When using `pytest.approx` you should provide a tolerance as well for IDAES I generally use `rel=1e-5` (i.e. 1 order of magnitude greater than solve tolerance). You should do this for both tests (the first one passes with the default tolerance, but I generally prefer to be explicit).

**Comment by bpaul4** [comment]
@andrewlee94 the second test passes when the tolerance is set to `rel=1E1` and this seems a bit large to me. Should I go ahead and push this change?

**Comment by bpaul4** [comment]
Yes. In the failure message above, the values seem very different from each other and now I'm suspecting something changed in the test module itself. We are comparing the same two quantities as the original test before the Boolean error occurred.

**Comment by andrewlee94** [comment]
If there is a difference in the values, then this problem goes deeper (and you will need to work out why).

**Comment by bpaul4** [comment]
The syntax seems correct and other test checks pass in the module using the same variables, so I believe this may be due to the PR_dai_dT equations inside the ceos module. @dallan-keylogic , would you have time to take a closer look at these equations and the chain rule expressions?

**Comment by andrewlee94** [comment]
@bpaul4 @dallan-keylogic As a note, it is not he expression that is the problem, it is a question of how it is being initialized/solved and why it is not getting the expected answer.

**Review by dallan-keylogic — APPROVED** [review]
I figured out what the problem was. I had incompletely cut and paste some stuff from Radhakrishna's test, and I suppose my incorrect call to `approx`  hid the issue before now. At first I thought it was being caused by side effects to the fixture because I was looking at the wrong test, so I also moved all code that modified the fixture `m` into the code defining that fixture.

**Review by lbianchi-lbl — APPROVED** [review]
I don't have enough domain knowledge to comment on the specific model and/or expression, but the changes look OK to me and they make pytest happy.

**Pull request merged**
