### PR TITLE
Fixing Modifying graph elements in the flowsheet

### LINKED ISSUE #913: Flowsheet diff crashes when unit is removed
When running the visualizer tutorial, if the saved file has F102 but the model does not (which happens when running again from the beginning), the flowsheet diff dumps the following stack trace:
```
------------------
model.fs.visualize("Hydrodealkylation")
------------------

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_38176\222046181.py in <cell line: 1>()
----> 1 model.fs.visualize("Hydrodealkylation")

c:\users\dangunter\src\idaes\dangunter\idaes-pse\idaes\core\base\flowsheet_model.py in visualize(self, model_name, **kwargs)
    238             None
    239         """
--> 240         visualize(self, model_name, **kwargs)
    241
    242     @deprecated(

c:\users\dangunter\src\idaes\dangunter\idaes-pse\idaes\core\ui\fsvis\fsvis.py in visualize(flowsheet, name, save, load_from_saved, save_dir, save_time_interval, overwrite, browser, port, log_level, quiet, loop_forever)
    166     # Add our flowsheet to it
    167     try:
--> 168         new_name = web_server.add_flowsheet(name, flowsheet, datastore)
    169     except (errors.ProcessingError, errors.DatastoreError) as err:
    170         raise errors.VisualizerError(f"Cannot add flowsheet: {err}")

c:\users\dangunter\src\idaes\dangunter\idaes-pse\idaes\core\ui\fsvis\model_server.py in add_flowsheet(self, id_, flowsheet, store)
    121         # First try to update, so as not to overwrite saved value
    122         try:
--> 123             self.update_flowsheet(id_)
    124         except errors.FlowsheetNotFoundInDatastore:
    125             _log.debug(f"No existing flowsheet found in {store}: saving new value")

c:\users\dangunter\src\idaes\dangunter\idaes-pse\idaes\core\ui\fsvis\model_server.py in update_flowsheet(self, id_)
    194             raise errors.ProcessingError(f"Cannot serialize flowsheet: {err}")
    195         # Compare saved and current value
--> 196         diff = FlowsheetDiff(saved, obj_dict)
    197         _log.debug(f"diff: {diff}")
    198         if not diff:

c:\users\dangunter\src\idaes\dangunter\idaes-pse\idaes\core\ui\flowsheet.py in __init__(self, old_flowsheet, new_flowsheet, validate)
    867         self._old, self._new = old_flowsheet, new_flowsheet
    868         self._len = None
--> 869         self._diff = self._compute_diff()
    870         self._layout = self._compute_layout() if self._diff else None
    871

c:\users\dangunter\src\idaes\dangunter\idaes-pse\idaes\core\ui\flowsheet.py in _compute_diff(self)
    927                         dest_unit_model = old_data[key]["dest"]
    928                         diff["change"]["unit_models"][src_unit_model] = copy.deepcopy(
--> 929                             new_model["unit_models"][src_unit_model]
    930                         )
    931                         diff["change"]["unit_models"][dest_unit_model] = copy.deepcopy(

KeyError: 'F102'
KeyError: 'F102'
```

### PR DESCRIPTION
**Pull request by elbashandy**
## Fixes
#913 

## Summary/Motivation:
Cleaning up the logic of merging updates between an old flowsheet and an new one in FlowsheetDiff

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by dangunter** [comment]
It works! -- but with a couple of little issues.
What I did was to the F101, F102 sequence in the example notebook *without* deleting the saved file in between. That worked quite well. Then I added this code to delete the F102 unit again:
```
del m.fs.s10
del m.fs.purity, m.fs.heating_cost
del m.fs.F102
TransformationFactory("network.expand_arcs").apply_to(m)
_ = vistut.initialize_model(m)
```
And when I hit refresh, voila, F102 goes away. There were some minor display issues though:
* I had toggled "show stream names" off, but when I refreshed the stream names showed up again; I had to toggle on/off to re-remove them
* The labels of units that I had rotated showed as rotated until I went and re-rotated them (at which point they corrected), for example:

image

Going to try re-adding and re-removing F102 to see if things still work.

**Review by dangunter — CHANGES_REQUESTED** [review]
See feedback in comment about rotated unit labels and stream labels. Once that's corrected I will look through code .. please add comments as needed.

**Comment by ksbeattie** [comment]
@dangunter will review

**Review by dangunter — APPROVED** [review]
Tested and all issues seem to be fixed.

**Review by ksbeattie — APPROVED** [review]
not sure I was able to entirely understand what the original problem was, but it LGTM now.

**Pull request merged**
