### PR TITLE
Adding a toggle to hide the stream names and show them

### PR DESCRIPTION
**Pull request by elbashandy**
## Summary/Motivation:
Adds Toggle to Streams' names in the flowsheet canvas

Screen Shot 2022-02-09 at 11 34 08 AM
Screen Shot 2022-02-09 at 11 34 15 AM

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by sspoon** [comment]
Functionality wise, I think this is great! I wonder if, since we have some thoughts about hiding the streams themselves, if we should label this toggle "Stream Names". I know it's not as clean as just Streams. We might as a separate task do some reorg of that menu, especially once we are able to show and hide it.

**Comment by dangunter** [comment]
@sspoon @elbashandy What about putting Show Stream Names and Show Unit Labels in the View menu instead, so the only toggle left standing would be "Grid"? I guess that could go too though for old times' sake I like it as toggle

**Comment by sspoon** [comment]
I think that would be ok. In general, all the things we put in the menu will be less easily discovered, vs controls directly on screen. But our list of toggles is getting rather large and potentially growing ... putting them in the menu could be a decent compromise.

**Review by ksbeattie — APPROVED** [review]
The functionality of this looks good to me (without any opinion on the title of the button or moving that into a menu item as discussed by @dangunter & @sspoon)

**Review by dangunter — APPROVED** [review]
LGTM

**Pull request merged**
