### PR TITLE
Update model data warning test

### PR DESCRIPTION
**Pull request by eslickj**
This updates a warning test to check that a warning is generated not that it is the only warning generated.  This came up here https://github.com/IDAES/idaes-pse/pull/131#issuecomment-828750774.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — APPROVED** [review]
Looks OK to me.

**Review by lbianchi-lbl — DISMISSED** [review]
LGTM :+1:

**Comment by eslickj** [comment]
@andrewlee94 and @lbianchi-lbl could you give this another review?  I messed it up the first time.  Should be work now.

**Review by andrewlee94 — APPROVED** [review]
Looks good.

**Review by lbianchi-lbl — APPROVED** [review]
Looks good

**Pull request merged**
