### PR TITLE
Moving base classes to core/base

### PR DESCRIPTION
**Pull request by andrewlee94**
## Summary/Motivation:
This PR moves all the base classes in `idaes.core` to `idaes.core.base` to help keep things organized as more models get moved into `idaes.core`.

After merge of #667, additional changes were added to this. `idaes.gas_distribution` and `idaes.generic_models.column_models` have been moved to the new folder `idaes.models_extra`. The MEA Column models have also been replaced by a simplified, general version.

## Changes proposed in this PR:
- Moves all the base classes to `idaes.core.base` along with their tests. Most components can still be imported from `idaes.core` however via the `__init__.py` file
- Updates all imports I could find
- Ran `black` on the new `idaes.core.base` folder
- Added deprecation paths for all base classes just in case
- Removed the `dmf/surrmod` module, as it was an interface to the deprecated ALAMO interface.
- Lots more after #667

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by eslickj — DISMISSED** [review]
Looks good to me.

**Comment by dangunter** [comment]
Looks reasonable. Are there any changes in the docs that you anticipate?

**Comment by andrewlee94** [comment]
@dangunter For now at least, no as we left things so that they can be imported `from `idaes.core` (which is what was used in the docs). Longer term, we might want to update the docs to better reflect the new repo structure.

**Review by eslickj — APPROVED** [review]

**Review by lbianchi-lbl — APPROVED** [review]
Proud to rubber-stamp!

**Review by lbianchi-lbl — APPROVED** [review]

**Review by eslickj — APPROVED** [review]

**Pull request merged**
