### PR TITLE
UI visual improvements

### PR DESCRIPTION
**Pull request by makaylas**
## Summary/Motivation:
UI improvements to match Sarah's mockup.

## Changes proposed in this PR:
- Lots of visual improvements
- Rappid toolbar is now a bootstrap navbar and a flexbox

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by makaylas** [comment]
@jghouse88 @andrewlee94 @MAZamarripa 

I don't need you to review the code so much as review the look of the UI. Here's a screenshot of it.

UI_after_improvements

**Review by ksbeattie — APPROVED** [review]
I ran `python idaes/ui/fsvis/tests/sample_visualization.py` and opened it in Firefox, Chrome and Safari on MacOS and it looks good.

**Comment by jghouse88** [comment]
@makaylas Thanks for the image. My only comment from the figure is the column `Variable` in the table below the flowsheet. The first 8 rows are only showing the index of the `flow_mol_phase_comp` variable but are not showing the actual var name. I think that is a bug...

**Comment by dangunter** [comment]
One minor thing I found is in the stream table, somehow -- and I can't reproduce it, so I'm not sure how --  I got to where the last couple of columns are narrower than the rest, even if you make the window wide enough to easily handle them. See image below. @makaylas if you can reproduce it, you can see if you can fix it.. but I think Refresh fixes it so not a big deal.

image

**Comment by dangunter** [comment]
Another minor thing I found was that the "Help" button doesn't open a new tab, so it essentially closes the UI. You should just add "target=_blank" to the HTML attrs.

**Comment by dangunter** [comment]
re: the stream table I take it back it is a bigger deal. I can reproduce it now. If you run the HDA Tutorial and put the call to visualize() at the *end* after the solve, the initial stream table has the problem of cutting off values.

image

**Comment by dangunter** [comment]
If I zoom out to 30%, say, the two panels are not the same size
image

**Comment by makaylas** [comment]
@dangunter for the zooming problem, what browser are you using? I can't reproduce it on Firefox, Chrome, or Safari

**Comment by makaylas** [comment]
@jghouse88 It's not a bug. That was a conscious choice we made. We removed the `flow_mol_phase_comp` because it didn't look nice and we didn't realize it was necessary.

Should I put that back in?

**Comment by makaylas** [comment]
@dangunter I made the Help button open a new tab.

**Review by dangunter — APPROVED** [review]
Looks good

**Review by lbianchi-lbl — COMMENTED** [review]
I looked at the code and everything seems fine. Should I do anything specific in addition to that for the review? Otherwise, I'm happy to approve.

**Comment by makaylas** [comment]
@lbianchi-lbl no, that's good. Thanks!

**Review by lbianchi-lbl — APPROVED** [review]

**Pull request merged**
