### PR TITLE
Change the OMLT version to 1.0 in setup.py

### PR DESCRIPTION
**Pull request by Xinhe-Chen**
## Summary/Motivation:
Open this draft PR to test that if there are some errors in the tests when the OMLT is updated to v1.0 in setup.py.
This is the issue related to this draft PR.
https://github.com/IDAES/idaes-pse/issues/982

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by andrewlee94** [comment]
@Xinhe-Chen What is the status on this PR? We are preparing for the next IDAES release this week, so if you want this to be included it needs to be merged by the end of the wee.

**Comment by Xinhe-Chen** [comment]
@andrewlee94 Hi Andrew, I am not working on this PR now. I think we have assigned this PR to the May 2023 release.

**Comment by andrewlee94** [comment]
@Xinhe-Chen I will close this for now then. You can reopen this when you are ready to merge.

**Comment by adowling2** [comment]
This PR also needs help from the surrogates team @carldlaird @OOAmusat

**Pull request closed without merging**
