### PR TITLE
Bumping the IDAES tag of Pyomo to check for issues

### PR DESCRIPTION
**Pull request by blnicho**
## Summary/Motivation:
Checking for issues ahead of the Pyomo release

## Changes proposed in this PR:
- Bumping the IDAES tag of Pyomo to test against Pyomo main

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
Converting it to draft while we wait for Pyomo/pyomo#3409 to be merged in, then we should un-draft it when this is ready to be merged (assuming all checks pass).

**Comment by blnicho** [comment]
We found a couple small issues with the 6.8.1 release so we're going to cut another patch release today. I'm converting this to a draft again so it doesn't get merged until we're finished cutting Pyomo 6.8.2.

**Review by lbianchi-lbl — APPROVED** [review]

**Comment by lbianchi-lbl** [comment]
@blnicho I've updated the pyomo requirement to point to the 6.8.2 release. Assuming the checks pass, I'm planning on merging this in. Let me know if there's any reason not to.

**Comment by blnicho** [comment]
@lbianchi-lbl this is ready to merge!

**Pull request merged**
