### PR TITLE
Update binary version to fix uncertainty tool with newer Pyomo

### PR DESCRIPTION
**Pull request by eslickj**
This just bumps the binary release number to get the updated version of k_aug the produces a more standard version string.  This should fix the problem with the uncertainty tool several people ran into recently.  There is also a secret solver.  The new Ipopt L1 restoration mode is available in an alternate Ipopt version called ipopt_l1 on all platforms except Cent OS 6 and 7.  It doesn't yet compile with the older compiler versions, but I figured this would at least let us do a little evaluation before officially releasing and announcing it. 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by eslickj** [comment]
Closing, as this doesn't seem to work.  I checked the k_aug repo again, and don't see any relevant changes for the version info recently.  I check a little bit ago when @Robbybp suggested I need a newer version of k_aug and it seemed to have been recently updated.  Not sure if I'm just confused or something weird happened.  Regardless this doesn't do what it's supposed to do.

**Comment by eslickj** [comment]
@Robbybp, looks like I was just wrong about the binaries.  They seem fine the issue is something about pysp.  I guess I probably need to update pyomo or something.

**Comment by Robbybp** [comment]
Okay, interesting. You might need https://github.com/Pyomo/pyomo/pull/1778 ? Or maybe The uncertainty toolbox relies on the prior version of Parmest?

**Comment by jsiirola** [comment]
FWIW, I have a patch (lbianchi-lbl/idaes-pse#8) in to @lbianchi-lbl's PR #292.  After both of those are merged, I think things will significantly stabalize.

**Comment by eslickj** [comment]
I just updated everything and tried again, and I'm back to k_aug not available.  The version string is definitely updated.  I guess I'll wait for things to shake out, and try again later.  Now I'm just going in circles somehow.

**Pull request closed without merging**
