### PR TITLE
Add tests for addtional solvers and Bump IDAES-EXT Version

### PR DESCRIPTION
**Pull request by eslickj**
## Changes proposed in this PR:

- Add tests for additional solvers
- Bump IDAES-EXT version to 2.4.0

Due to my unfortunate testing setup, I have a bit of a chicken and egg problem.  I need to merge this before I can run the full set of tests all solvers on all platforms.  If it passes here but not in the more comprehensive tests with CentOS and additional Ubuntu releases, I'll quickly make a 2.4.1 release.  I'm 90% sure everything works, and pretty much 100% sure Ipopt at least works everywhere, so this shouldn't break things for anyone.  

I'd like merge this ASAP so I can finish up the testing and stop messing with this.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — DISMISSED** [review]
Looks OK to me. Only minor comment was that I didn't see an IPOPT test in there, but that is minor (and it's not like we don't have tests which use it).

**Comment by eslickj** [comment]
@andrewlee94, Ipopt is so important it already has it's very own test file.

**Review by lbianchi-lbl — DISMISSED** [review]
Looks good as far as I can tell.

**Comment by eslickj** [comment]
@andrewlee94 and @lbianchi-lbl, sorry I forgot to push the change to increment the binary release version.  Could you re-review.

**Review by andrewlee94 — DISMISSED** [review]
Looks good.

**Review by lbianchi-lbl — APPROVED** [review]

**Comment by eslickj** [comment]
@lbianchi-lbl, there is a problem I ran into here with the github action for installing IDAES.  I think we should skip the part that tries to run ipopt after running get extensions.  Using ipopt from an IDAES model does not require updating PATH.  We'll also see that ipopt is missing later in the tests if somehow it wasn't installed without running into an error.  Alternatively we can keep the Ipopt check in the action, but you'll need to update LD_LIBRARY_PATH as well now.

**Comment by lbianchi-lbl** [comment]
@eslickj This makes sense, I added the check without being too aware of the internals, but as I understand from what you're saying, it doesn't add anything that it's not already provided within IDAES.

If you're OK with it, I can get rid of that step in the GH Actions workflows, and push the changes directly on your branch for this PR.

**Comment by eslickj** [comment]
@lbianchi-lbl, sounds good.  Thanks for updating it.

**Review by andrewlee94 — APPROVED** [review]
I will assume that everyone knows what they are doing.

**Review by lbianchi-lbl — APPROVED** [review]
:+1:

**Pull request merged**
