### PR TITLE
Changes related to finalizing power plant costing module

### PR DESCRIPTION
**Pull request by bpaul4**
I listed corrections made in the "Fixes" section below, and additions made in the "Change proposed in this PR" section below.

## Fixes
- Added `capacity_factor` as argument to main `build_process_costs` method, and divide operating costs by capacity factor to get scaled costs at 100% plant capacity
- Added `fixed_TPC` as argument to `get_fixed_OM_costs` method
- More robust checking for `land_cost` Pyomo units
- In `get_fixed_OM_costs` method, wrapped `fixed_TPC` in a `value()` call to fix an error assigning the value to `total_TPC`
- A small correction to the total TPC check in `test_NGCC_capcost.py::test_flowsheet_costing`, which changed as a result of the slight changes to the TOC calculation
- `black` and other formatting changes for readability
- “6” “A” account 11.8, RP Value set to 830000 (reference: NETL baseline report rev 4 Case B31A, Account 11: Accessory Electric Plant, equipment no 1 and 2)
- “6” “B” account 11.8 RP Value set to 740000 (reference: NETL baseline report rev 4 Case B31B, Account 11: Accessory Electric Plant, equipment no 1 and 2)

## Changes proposed in this PR:
- Updated author list (reviewers, please comment if any contributors are missing)
- Added `chemicals_inventory` as a distinct resource type from `chemicals` costs to prevent inclusion of initial fill costs for non-inventory chemicals; leads to a small reduction in total TOC and TPC
- Added `transport_cost` as a cost type
- Minor changes and additions to the `report` method
- Updates to the documentation as needed
- New tests as needed for coverage

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
This doesn't have to be in the May release.

**Comment by bpaul4** [comment]
The two failing tests are code coverage and ReadTheDocs. Regarding coverage, I believe the new tests cover as much as can reasonably be tested and the failure is a quirk of 'codecov''s checking functionality. The ReadTheDocs failure was mentioned by @lbianchi-lbl as a known bug.

**Review by MAZamarripa — APPROVED** [review]
lgtm

**Comment by ksbeattie** [comment]
@bpaul4 will this be part of the May release?  As in, done by next week?

**Comment by bpaul4** [comment]
@ksbeattie yes, the second reviewer will take a look today and the plan is to merge ASAP - I will follow up with you offline. Thank you!

**Review by AlexNoring — APPROVED** [review]
lgtm

**Pull request merged**
